name: Checks

on:
  push:
    branches: [main]

jobs:
  check:
    name: Lint, Type, Coverage & Build
    uses: ./.github/workflows/check.yml
    with:
      upload-coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}